version: '3.8'

services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    ports:
      - "9992:5432"
    environment:
      POSTGRES_DB: expense-monitor-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres_test_db:
    image: postgres
    container_name: postgres_test_db
    ports:
      - "9993:5432"
    environment:
      POSTGRES_DB: expense-monitor-service-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  expense-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-monitor
    ports:
      - "9990:9990"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/expense-monitor-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 9990
    depends_on:
      - postgres_db
