create table exchange_rates (
                                id bigint generated by default as identity,
                                currency_pair varchar(255) not null,
                                date date not null,
                                rate float(53) not null,
                                primary key (id)
);

create table limits (
                        id bigint generated by default as identity,
                        expense_category varchar(255) not null,
                        limit_currency_shortname varchar(255),
                        limit_datetime timestamp(6) with time zone not null,
                        limit_sum numeric(38,2),
                        limit_sum_usd numeric(38,2) not null,
                        account_from bigint not null ,
                        primary key (id)
);

create table transactions (
                              id bigint generated by default as identity,
                              account_from bigint not null,
                              account_to bigint not null,
                              currency_shortname varchar(255) not null,
                              datetime timestamp(6) with time zone not null,
                              expense_category varchar(255) not null,
                              limit_exceeded boolean not null,
                              remaining_limit_usd numeric(38,2) not null,
                              sum numeric(38,2) not null,
                              sum_usd numeric(38,2) not null,
                              limit_id bigint REFERENCES limits(id),
                              primary key (id)
);
